var height = "你好同学";
alert(height);
var he = "进来你就出不去了";
alert(he);
var he = "你不信？";
alert(he);
var he = "那你就继续点确定";
alert(he);
var he = "你点吧";
alert(he);
var he = "你再点一下试试";
alert(he);
var he = "你猜点到第几下可以出去";
alert(he);
var he = "我告诉你一个秘密";
alert(he);
var he = "你先点几下我再告诉你";
alert(he);
var he = "再点一下我告诉你";
alert(he);
var he = "再试一次";
alert(he);
var he = "继续";
alert(he);
var he = "继续点";
alert(he);
var he = "不要停";
alert(he);
var he = "你不如数数你点了几下";
alert(he);
var he = "1";
alert(he);
var he = "1";
alert(he);
var he = "恭喜你到达了程序的终点";
alert(he);